output_dir: "out/sft_math"
run_name: "sft-math"
report_to: "swanlab"
max_length: 1024
num_train_epochs: 5
learning_rate: 5e-6
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
per_device_eval_batch_size: 4
logging_steps: 10
eval_strategy: "steps"
eval_steps: 500

save_strategy: "epoch"
remove_unused_columns: false
bf16: true
fp16: false
dataset_text_field: "text"