output_dir: "out/grpo_math"
run_name: "grpo-math"
report_to: "swanlab"

learning_rate: 5e-6
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
per_device_eval_batch_size: 8
num_generations_eval: 1

#num_train_epochs: 1
max_steps: 2000
generation_batch_size: 8


logging_steps: 10

eval_strategy: "steps"
eval_steps: 200
save_strategy: "steps"
save_steps: 500


max_completion_length: 1024
num_generations: 8

beta: 0.0

bf16: true
fp16: false
remove_unused_columns: false

